from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        
        self.label_pid = QtWidgets.QLabel(self.centralwidget)
        self.label_pid.setObjectName("label_pid")
        self.inputLayout.addWidget(self.label_pid)
        self.pid_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pid_input.setObjectName("pid_input")
        self.inputLayout.addWidget(self.pid_input)
        
        self.label_arr = QtWidgets.QLabel(self.centralwidget)
        self.label_arr.setObjectName("label_arr")
        self.inputLayout.addWidget(self.label_arr)
        self.arr_input = QtWidgets.QSpinBox(self.centralwidget)
        self.arr_input.setObjectName("arr_input")
        self.arr_input.setMaximum(9999)
        self.inputLayout.addWidget(self.arr_input)
        
        self.label_burst = QtWidgets.QLabel(self.centralwidget)
        self.label_burst.setObjectName("label_burst")
        self.inputLayout.addWidget(self.label_burst)
        self.burst_input = QtWidgets.QSpinBox(self.centralwidget)
        self.burst_input.setObjectName("burst_input")
        self.burst_input.setMaximum(9999)
        self.inputLayout.addWidget(self.burst_input)
        
        self.label_prio = QtWidgets.QLabel(self.centralwidget)
        self.label_prio.setObjectName("label_prio")
        self.inputLayout.addWidget(self.label_prio)
        self.prio_input = QtWidgets.QSpinBox(self.centralwidget)
        self.prio_input.setObjectName("prio_input")
        self.prio_input.setMaximum(9999)
        self.inputLayout.addWidget(self.prio_input)
        
        self.addProcessButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProcessButton.setObjectName("addProcessButton")
        self.inputLayout.addWidget(self.addProcessButton)
        
        self.gridLayout.addLayout(self.inputLayout, 2, 0, 1, 5)

        self.comparison = QtWidgets.QLabel(self.centralwidget)
        self.comparison.setObjectName("comparison")
        self.gridLayout.addWidget(self.comparison, 7, 0, 1, 2)
        
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_2, 4, 0, 1, 5)
        
        self.scenarioB_Button = QtWidgets.QPushButton(self.centralwidget)
        self.scenarioB_Button.setObjectName("scenarioB_Button")
        self.gridLayout.addWidget(self.scenarioB_Button, 1, 1, 1, 1)
        self.priorityButton = QtWidgets.QPushButton(self.centralwidget)
        self.priorityButton.setObjectName("priorityButton")
        self.gridLayout.addWidget(self.priorityButton, 1, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 5, 0, 1, 5)
        self.scenarioA_Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.scenarioA_Button_2.setObjectName("scenarioA_Button_2")
        self.gridLayout.addWidget(self.scenarioA_Button_2, 1, 0, 1, 1)
        self.SRTFButton = QtWidgets.QPushButton(self.centralwidget)
        self.SRTFButton.setObjectName("SRTFButton")
        self.gridLayout.addWidget(self.SRTFButton, 1, 3, 1, 1)
        self.compareButton = QtWidgets.QPushButton(self.centralwidget)
        self.compareButton.setObjectName("compareButton")
        self.gridLayout.addWidget(self.compareButton, 1, 4, 1, 1)
        self.gantt = QtWidgets.QLabel(self.centralwidget)
        self.gantt.setObjectName("gantt")
        self.gridLayout.addWidget(self.gantt, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName("menubar")
        self.menuOS_PROJECT = QtWidgets.QMenu(self.menubar)
        self.menuOS_PROJECT.setObjectName("menuOS_PROJECT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOS_PROJECT.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.addProcessButton.clicked.connect(self.add_process)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OS Scheduler"))
        
        self.label_pid.setText(_translate("MainWindow", "Process ID:"))
        self.label_arr.setText(_translate("MainWindow", "Arrival Time:"))
        self.label_burst.setText(_translate("MainWindow", "Burst Time:"))
        self.label_prio.setText(_translate("MainWindow", "Priority:"))
        self.addProcessButton.setText(_translate("MainWindow", "Add Process"))

        self.comparison.setText(_translate("MainWindow", "Comparison"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Arrival_Time"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Burst_Time"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Priority"))
        self.scenarioB_Button.setText(_translate("MainWindow", "Scenario B"))
        self.priorityButton.setText(_translate("MainWindow", "Run Priority"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Waiting_Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Turnaround_Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Response time"))
        self.scenarioA_Button_2.setText(_translate("MainWindow", "Scenario A"))
        self.SRTFButton.setText(_translate("MainWindow", "Run SRTF"))
        self.compareButton.setText(_translate("MainWindow", "Compare"))
        self.gantt.setText(_translate("MainWindow", "Gantt charts"))
        self.menuOS_PROJECT.setTitle(_translate("MainWindow", "OS PROJECT"))

    def add_process(self):
        pid = self.pid_input.text()
        arrival = str(self.arr_input.value())
        burst = str(self.burst_input.value())
        priority = str(self.prio_input.value())

        if not pid.strip():
            return

        row_position = self.tableWidget_2.rowCount()
        self.tableWidget_2.insertRow(row_position)

        self.tableWidget_2.setItem(row_position, 0, QtWidgets.QTableWidgetItem(pid))
        self.tableWidget_2.setItem(row_position, 1, QtWidgets.QTableWidgetItem(arrival))
        self.tableWidget_2.setItem(row_position, 2, QtWidgets.QTableWidgetItem(burst))
        self.tableWidget_2.setItem(row_position, 3, QtWidgets.QTableWidgetItem(priority))

        self.pid_input.clear()
        self.arr_input.setValue(0)
        self.burst_input.setValue(0)
        self.prio_input.setValue(0)
        
        self.pid_input.setFocus()