# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.priorityButton = QtWidgets.QPushButton(self.centralwidget)
        self.priorityButton.setObjectName("priorityButton")
        self.gridLayout.addWidget(self.priorityButton, 0, 0, 1, 1)
        self.SRTFButton = QtWidgets.QPushButton(self.centralwidget)
        self.SRTFButton.setObjectName("SRTFButton")
        self.gridLayout.addWidget(self.SRTFButton, 0, 1, 1, 1)
        self.scenarioButton = QtWidgets.QPushButton(self.centralwidget)
        self.scenarioButton.setObjectName("scenarioButton")
        self.gridLayout.addWidget(self.scenarioButton, 0, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 4)
        self.comparison = QtWidgets.QLabel(self.centralwidget)
        self.comparison.setObjectName("comparison")
        self.gridLayout.addWidget(self.comparison, 2, 0, 1, 2)
        self.compareButton = QtWidgets.QPushButton(self.centralwidget)
        self.compareButton.setObjectName("compareButton")
        self.gridLayout.addWidget(self.compareButton, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 21))
        self.menubar.setObjectName("menubar")
        self.menuOS_PROJECT = QtWidgets.QMenu(self.menubar)
        self.menuOS_PROJECT.setObjectName("menuOS_PROJECT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOS_PROJECT.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.priorityButton.setText(_translate("MainWindow", "Run Priority"))
        self.SRTFButton.setText(_translate("MainWindow", "Run SRTF"))
        self.scenarioButton.setText(_translate("MainWindow", "Scenario A / B"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Waiting_Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Turnaround_Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Response time"))
        self.comparison.setText(_translate("MainWindow", "Comparison"))
        self.compareButton.setText(_translate("MainWindow", "Compare"))
        self.menuOS_PROJECT.setTitle(_translate("MainWindow", "OS PROJECT"))
